repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        args: [--strict]
-   repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/pylint
    rev: v3.1.0
    hooks:
    -   id: pylint
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
